name = "SimpleRadiativeTransfer"
uuid = "d9671a99-3ca0-4253-904b-b84b72e7f5e1"
authors = ["Thomas Dubos <thomas.dubos@polytechnique.edu> and contributors"]
version = "0.1.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
